feat(install): add support configurable installation

diff --git a/scripts/utils b/scripts/utils
--- a/scripts/utils
+++ b/scripts/utils
@@ -195,13 +195,27 @@ user_can_sudo() {
     ! LANG= sudo -n -v 2>&1 | grep -q "may not run sudo"
 }
 
-prompt() {
-    printf '%s%s%s' "${FMT_YELLOW}" "$1" "${FMT_RESET}" >&2
-    read -p " ${FMT_BOLD}[y/N]${FMT_RESET} " a
-    if [[ $a == "y" || $a == "Y" ]]; then
-        return 0
+run_as_root() {
+    if command -v sudo >/dev/null 2>&1; then
+        sudo sh -c "${*}"
+    else
+        su -c "${*}"
     fi
-    return 1
+}
+
+prompt() {
+    while true; do
+        printf '%s%s%s' "${FMT_YELLOW}" "$1" "${FMT_RESET}" >&2
+        read -rp " ${FMT_BOLD}[y/n]${FMT_RESET} " yn
+        case "${yn}" in
+            [Yy]*) return 0 ;;
+            [Nn]*) return 1 ;;
+            *)
+                error "Please answer y or n"
+                printf '\n' >&2
+                ;;
+        esac
+    done
 }
 
 underline() {
@@ -210,14 +224,18 @@ underline() {
 
 link() {
     # $1: text, $2: url, $3: fallback mode
+    local text="${1}"
+    local url="${2:-${text}}"
+    local fallback="${3:-${url}}"
+
     if supports_hyperlinks; then
-        printf '\033]8;;%s\033\\%s\033]8;;\033\\' "$2" "$1"
+        printf '\033]8;;%s\033\\%s\033]8;;\033\\' "$url" "$text"
         return
     fi
 
-    case "$3" in
-    --text) printf '%s\n' "$1" ;;
-    --url | *) underline "$2" ;;
+    case "${fallback}" in
+    --text) printf '%s\n' "$text" ;;
+    --url | *) underline "$url" ;;
     esac
 }
 
@@ -227,8 +245,8 @@ fmt_code() {
 }
 
 codeblock() {
-    fmt_code $* >&2
-    printf '\n' >&2
+    fmt_code "$*"
+    printf '\n'
 }
 
 success() {
@@ -306,9 +324,56 @@ header() {
 #     echo
 # }
 
+abspath(){
+    readlink --canonicalize-missing "$1"
+}
+
+is_in() {
+    local check="${1}"
+    shift
+    local items=("${@}")
+
+    for item in "${items[@]}"; do
+        if [[ "${check}" == "${item}" ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
 # Test whether we're in a git repo
 is_git_repo() {
     $(git rev-parse --is-inside-work-tree &> /dev/null)
+}
+
+rcurl() {
+    URL="${1:-}"
+
+    # Attempt to make all curl commands more resilient to failure. The speed
+    # flags help protect against zombie connections while still allowing long
+    # downloads on slower connections (avoiding --max-time).
+    #
+    # At the same time, let stderr get printed in real-time. If errors occur,
+    # producee a final error message so folks know we cannot continue.
+    args=(
+        "--silent"
+        "--show-error"
+        "--fail"
+        "--connect-timeout" "10"
+        "--retry" "4"
+        "--retry-all-errors"
+        "--speed-limit" "100"
+        "--speed-time" "30"
+        "--location"
+    )
+
+    args+=("${@}")
+
+    if ! curl "${args[@]}"; then
+        error "'${URL}' didn't respond successfully, retry or check your connection, aborting!"
+        return 1
+    fi
 }
 
 # Detect the OS/distribution
@@ -322,7 +387,7 @@ detect_os() {
     # Check for macOS first
     if [[ "$OSTYPE" == "darwin"* ]]; then
         OS_TYPE="darwin"
-        OS_DISTRO="${OS_TYPE}"
+        OS_DISTRO="macos"
         OS_DISTRO_ORIGINAL="${OS_DISTRO}"
         OS_DISTRO_LIKE="${OS_DISTRO}"
     fi
@@ -407,6 +472,17 @@ detect_os() {
     # at least protects someone running this script who didn't pass in the
     # environment variable in the common case (Docker or Podman).
     [[ -f "/.dockerenv" || -f "/run/.containerenv" ]] && OS_IN_CONTAINER="yes"
+
+    # Can we install and configure a window manager and GUI tools?
+    if [[ "${OS_TYPE}" == "linux" && "${OS_DISTRO_LIKE}" = "arch" && "${OS_IN_WSL}" != "yes" && "${OS_IN_CONTAINER}" != "yes" ]]; then
+        DOTY_GUI_ELIGIBLE="yes"
+    fi
+
+    if [[ "${DOTY_GUI_ENABLED}" == "yes" && "${DOTY_GUI_ELIGIBLE}" == "yes" ]]; then
+        DOTY_GUI_ENABLED="yes"
+    else
+        DOTY_GUI_ENABLED="no"
+    fi
 }
 
 setup_color
